AppBundle\Entity\Spaceman:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        birthdate:
            - NotBlank: ~
        superPower:
            - NotBlank: ~
